# Jvm info
java_version=25
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

## Mod info
mod_id=eyesinair
mod_name=AnvilCraft: Void in Air
mod_description=An AnvilCraft addon has something imaginative.
mod_license=LGPL-3.0 license
mod_version=1.0.0
mod_url=https://github.com/QiuShui1012/AnvilCraft-VoidinAir

#Development info
maven_group=com.qiushui1012.mod

minecraft_version_range=[26.1,26.2)
