# Jvm info
java_version=21
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Mod info
mod_id=voidinair
mod_name=AnvilCraft: Void in Air
mod_description=An AnvilCraft addon has something imaginative.
mod_author=QiuShui1012
mod_license=LGPL-3.0-or-later
mod_version=1.2.1
mod_url=https://github.com/QiuShui1012/AnvilCraft-VoidInAir

# Development info
maven_group=com.qiushui1012.mod

minecraft_version_range=[1.21,1.21.1)
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

# Publish Info
ci_mod_name=AnvilCraft Void in Air
modrinth_id=9SySIjXk
curseforge_id=1552581
